### ISSUE TITLE
Couldn't retrieve uid b'116'

### ISSUE THREAD

**Issue by mflage** [rtucker/imap2maildir#30]
Attempting to download a regular IMAP folder I'm getting the following traceback:

> Synchronizing 23 messages from hostname:INBOX to /home/marius/hostname/username...
> ERROR:root:Couldn't retrieve uid b'116'
> Traceback (most recent call last):
>   File "/home/marius/src/imap2maildir/simpleimap.py", line 445, in Summaries
>     summ = self.__parent.get_summary_by_uid(u)
>   File "/home/marius/src/imap2maildir/simpleimap.py", line 303, in get_summary_by_uid
>     return self.parse_summary_data(data)
>   File "/home/marius/src/imap2maildir/simpleimap.py", line 334, in parse_summary_data
>     combined_data = ' '.join(data)
> TypeError: sequence item 0: expected str instance, bytes found
> FINISHED: Turboed 0, handled 0, copied 0 (0 bytes), last UID was 0
> INFO:__main__:FINISHED: Turboed 0, handled 0, copied 0 (0 bytes), last UID was 0

The command I'm using is:

> $ ./imap2maildir.py -H hostname -u username -d <path> -r "INBOX"  --create

**Comment by leaumar** [comment]
I got the same when I ran with python3. Try running it with python2 as mentioned in #24 ?
